spring.application.name=api

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.datasource.url=jdbc:oracle:thin:@//localhost:1530/ORCLPDB1
spring.datasource.username=TEST_SCHEMA
spring.datasource.password=test123schema
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

app.version=Calculator API v1.0.0